/*
 * peripheral/evic/plib_evic.h — EVIC PLIB stub for QEMU FreeRTOS test build.
 *
 * In the real firmware this is auto-generated by MHC and provides EVIC register
 * access using the XC32 register abstraction. Here we provide inline equivalents
 * using direct volatile register access, matching xc.h conventions.
 *
 * EVIC register layout (PIC32MK, EVIC base = 0xBF810000):
 *   IFSn: base + 0x0040 + n*0x10  (read/write)
 *   IFSn_CLR: base + 0x0044 + n*0x10
 *   IFSn_SET: base + 0x0048 + n*0x10
 *   IECn: base + 0x00C0 + n*0x10  (read/write)
 *   IECn_CLR: base + 0x00C4 + n*0x10
 *   IECn_SET: base + 0x00C8 + n*0x10
 *
 * For source N: n = N/32, bit = N%32.
 *
 * Copyright (c) 2026 QEMU contributors
 * SPDX-License-Identifier: GPL-2.0-or-later
 */
#ifndef PLIB_EVIC_H
#define PLIB_EVIC_H

#include <stdint.h>
#include <stdbool.h>

/* Interrupt source numbers matching XC32 p32mk1024mcm100.h vectors */
#define _USB_1_VECTOR   34U
#define _USB_2_VECTOR   244U

typedef uint32_t INT_SOURCE;
#define INT_SOURCE_USB_1   _USB_1_VECTOR
#define INT_SOURCE_USB_2   _USB_2_VECTOR

/* -----------------------------------------------------------------------
 * EVIC inline functions
 * ----------------------------------------------------------------------- */

#define _EVIC_BASE  0xBF810000u

static inline void EVIC_SourceEnable(INT_SOURCE source)
{
    uint32_t reg = source >> 5u;
    uint32_t bit = source & 31u;
    /* IECn_SET = EVIC_BASE + 0x00C8 + reg*0x10 */
    *(volatile uint32_t *)(_EVIC_BASE + 0x00C8u + reg * 0x10u) = (1u << bit);
}

static inline bool EVIC_SourceDisable(INT_SOURCE source)
{
    uint32_t reg = source >> 5u;
    uint32_t bit = source & 31u;
    uint32_t iec = *(volatile uint32_t *)(_EVIC_BASE + 0x00C0u + reg * 0x10u);
    bool was_enabled = (bool)((iec >> bit) & 1u);
    /* IECn_CLR = EVIC_BASE + 0x00C4 + reg*0x10 */
    *(volatile uint32_t *)(_EVIC_BASE + 0x00C4u + reg * 0x10u) = (1u << bit);
    return was_enabled;
}

static inline bool EVIC_SourceIsEnabled(INT_SOURCE source)
{
    uint32_t reg = source >> 5u;
    uint32_t bit = source & 31u;
    uint32_t iec = *(volatile uint32_t *)(_EVIC_BASE + 0x00C0u + reg * 0x10u);
    return (bool)((iec >> bit) & 1u);
}

static inline bool EVIC_SourceStatusGet(INT_SOURCE source)
{
    uint32_t reg = source >> 5u;
    uint32_t bit = source & 31u;
    uint32_t ifs = *(volatile uint32_t *)(_EVIC_BASE + 0x0040u + reg * 0x10u);
    return (bool)((ifs >> bit) & 1u);
}

static inline void EVIC_SourceStatusSet(INT_SOURCE source)
{
    uint32_t reg = source >> 5u;
    uint32_t bit = source & 31u;
    /* IFSn_SET = EVIC_BASE + 0x0048 + reg*0x10 */
    *(volatile uint32_t *)(_EVIC_BASE + 0x0048u + reg * 0x10u) = (1u << bit);
}

static inline void EVIC_SourceStatusClear(INT_SOURCE source)
{
    uint32_t reg = source >> 5u;
    uint32_t bit = source & 31u;
    /* IFSn_CLR = EVIC_BASE + 0x0044 + reg*0x10 */
    *(volatile uint32_t *)(_EVIC_BASE + 0x0044u + reg * 0x10u) = (1u << bit);
}

/* Global interrupt enable/disable (used by osal_freertos.h internally) */
static inline void EVIC_INT_Enable(void)
{
    __asm__ volatile("ei; ehb" : : : "memory");
}

static inline bool EVIC_INT_Disable(void)
{
    uint32_t status;
    __asm__ volatile("di %0; ehb" : "=r"(status));
    return (bool)(status & 1u);
}

static inline void EVIC_INT_Restore(bool state)
{
    if (state) {
        __asm__ volatile("ei; ehb" : : : "memory");
    }
}

#endif /* PLIB_EVIC_H */
